packages:
  - packages/*

allowBuilds:
  unrs-resolver: true

blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@frontify/*'
  # Renovate security update: brace-expansion@1.1.21
  - brace-expansion@1.1.21
